---
- hosts: idm
  vars:
    idm_ds_password:  "SuperSecretPassword123"
    idm_admin_password: "SuperSecretPassword123"
    realm:  "myork"
    domain: "myork"
    hostname: "idm"
    reversename: "200.168.192.in-addr.arpa."
    ip_address: "192.168.200.23"
    inventory_hostname: idm.myork
    rhsm_hostname: subscription.rhn.redhat.com
    rhsm_pool: '^Employee SKU$'

    # If se to no then the dns will not be configured
    setup_dns: yes

    # User DNS forwarders
    use_dns_forwarders: no
    dns_forwarder_ip: 192.168.200.1


  vars_prompt:
    - name: "rhsm_username"
      prompt: "Please enter your RHN Username"
      private: no

    - name: "rhsm_password"
      prompt:  "Please enter your RHN password"
      private: yes

  roles:
     - role:  idm