---
  - name: Restart server
    become: yes
    shell: sleep 2 && /sbin/shutdown -r now "Ansible system package upgraded"
    async: 1
    poll: 0

  - name: waiting 60 secs for server to come back
    local_action: wait_for host=192.168.200.23 port=22 delay=20 connect_timeout=200
    become: false
    delegate_to:  127.0.0.1